import { API_CONFIG } from '@/constants/Config';
import { useTheme } from '@/context/ThemeContext';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React, { useEffect, useState } from 'react';
import {
    ActivityIndicator,
    Platform,
    ScrollView,
    Share,
    StyleSheet,
    Text,
    TouchableOpacity,
    View
} from 'react-native';

interface DigestDetail {
  id: string;
  topic: string;
  content: string;
  generatedAt: string;
  deliveredAt?: string;
  customPrompt?: string;
  sources?: string[];
}

export default function DigestDetailPage() {
  const { colors } = useTheme();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [digest, setDigest] = useState<DigestDetail | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadDigest();
  }, [id]);

  const loadDigest = async () => {
    if (!id) return;
    
    try {
      const response = await fetch(`${API_CONFIG.BASE_URL}/api/digest/${id}`);
      const result = await response.json();
      
      if (result.success) {
        setDigest(result.digest);
      }
    } catch (error) {
      console.error('Failed to load digest:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async () => {
    if (!digest) return;
    try {
      await Share.share({
        message: `📰 *${digest.topic} Daily Digest*\n\n${digest.content}\n\nGenerated by Monox AI`,
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const handleDelete = () => {
    const doDelete = async () => {
      try {
        await fetch(`${API_CONFIG.BASE_URL}/api/digest/${id}`, {
          method: 'DELETE',
        });
        router.back();
      } catch (error) {
        if (Platform.OS === 'web') {
          window.alert('Failed to delete digest');
        } else {
          require('react-native').Alert.alert('Error', 'Failed to delete digest');
        }
      }
    };

    if (Platform.OS === 'web') {
      const ok = window.confirm('Are you sure you want to delete this digest?');
      if (ok) doDelete();
    } else {
      const NativeAlert = require('react-native').Alert;
      NativeAlert.alert(
        'Delete Digest',
        'Are you sure you want to delete this digest?',
        [
          { text: 'Cancel', style: 'cancel' },
          { text: 'Delete', style: 'destructive', onPress: doDelete }
        ]
      );
    }
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('id-ID', {
      weekday: 'long',
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const renderContent = (content: string) => {
    const lines = content.split('\n');
    return lines.map((line, index) => {
      // Bold handling: **text**
      const parts = line.split(/(\*\*.*?\*\*)/g);
      
      return (
        <Text key={index} style={[styles.contentText, { color: colors.text }]}>
          {parts.map((part, i) => {
            if (part.startsWith('**') && part.endsWith('**')) {
              return (
                <Text key={i} style={{ fontWeight: '700', color: colors.primary }}>
                  {part.replace(/\*\*/g, '')}
                </Text>
              );
            }
            return <Text key={i}>{part}</Text>;
          })}
        </Text>
      );
    });
  };

  if (loading) {
    return (
      <View style={[styles.container, styles.centered, { backgroundColor: colors.background }]}>
        <ActivityIndicator size="large" color={colors.primary} />
      </View>
    );
  }

  if (!digest) {
    return (
      <View style={[styles.container, styles.centered, { backgroundColor: colors.background }]}>
        <Ionicons name="alert-circle-outline" size={64} color={colors.textSecondary} />
        <Text style={[styles.errorText, { color: colors.textSecondary }]}>
          Digest not found
        </Text>
        <TouchableOpacity
          style={[styles.backBtn, { backgroundColor: colors.primary }]}
          onPress={() => router.back()}
        >
          <Text style={styles.backBtnText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      {/* Header */}
      <View style={[styles.header, { borderBottomColor: colors.border }]}>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={24} color={colors.text} />
        </TouchableOpacity>
        
        <View style={styles.headerRight}>
          <TouchableOpacity style={styles.iconButton} onPress={handleShare}>
            <Ionicons name="share-outline" size={24} color={colors.primary} />
          </TouchableOpacity>
          <TouchableOpacity style={styles.iconButton} onPress={handleDelete}>
            <Ionicons name="trash-outline" size={24} color="#FF6B6B" />
          </TouchableOpacity>
        </View>
      </View>

      {/* Content */}
      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Title Section */}
        <View style={styles.titleSection}>
          <View style={styles.topicBadge}>
            <Ionicons name="newspaper" size={16} color={colors.primary} />
            <Text style={[styles.topicText, { color: colors.primary }]}>{digest.topic}</Text>
          </View>
          <Text style={[styles.title, { color: colors.text }]}>
            Daily Digest
          </Text>
          <Text style={[styles.date, { color: colors.textSecondary }]}>
            {formatDate(digest.deliveredAt || digest.generatedAt)}
          </Text>
        </View>

        {/* Custom Prompt if exists */}
        {digest.customPrompt && (
          <View style={[styles.promptCard, { backgroundColor: colors.primary + '15', borderColor: colors.primary }]}>
            <Ionicons name="sparkles" size={16} color={colors.primary} />
            <Text style={[styles.promptText, { color: colors.text }]}>
              {digest.customPrompt}
            </Text>
          </View>
        )}

        {/* Main Content */}
        <View style={[styles.contentCard, { backgroundColor: colors.cardBackground }]}>
          {renderContent(digest.content)}
        </View>

        {/* Sources if available */}
        {digest.sources && digest.sources.length > 0 && (
          <View style={styles.sourcesSection}>
            <Text style={[styles.sourcesTitle, { color: colors.textSecondary }]}>
              Sources
            </Text>
            {digest.sources.map((source, index) => (
              <Text key={index} style={[styles.sourceLink, { color: colors.primary }]}>
                • {source}
              </Text>
            ))}
          </View>
        )}

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 48,
    borderBottomWidth: 1,
  },
  backButton: {
    padding: 8,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButton: {
    padding: 8,
  },
  topicBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  topicText: {
    fontSize: 14,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  titleSection: {
    marginBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
  },
  date: {
    fontSize: 15,
  },
  promptCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 24,
  },
  promptText: {
    flex: 1,
    fontSize: 14,
    fontStyle: 'italic',
  },
  contentCard: {
    borderRadius: 16,
    padding: 20,
  },
  contentText: {
    fontSize: 16,
    lineHeight: 28,
    marginBottom: 12,
  },
  sourcesSection: {
    marginTop: 24,
    padding: 16,
  },
  sourcesTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
  },
  sourceLink: {
    fontSize: 14,
    marginBottom: 8,
    textDecorationLine: 'underline',
  },
  errorText: {
    fontSize: 18,
    fontWeight: '600',
    marginTop: 16,
    marginBottom: 24,
  },
  backBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  backBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});
